### PR TITLE
Please open your bug tracker

### PR DESCRIPTION
**Pull request by Rudd-O**
Do not merge this!

There's a problem with static compilation on F24:

```
CMakeFiles/nheqminer.dir/libstratum/StratumClient.cpp.o: In function `boost::asio::detail::resolver_service<boost::asio::ip::tcp>::resolve(std::shared_ptr<void>&, boost::asio::ip::basic_resolver_query<boost::asio::ip::tcp> const&, boost::system::error_code&)':
StratumClient.cpp:(.text._ZN5boost4asio6detail16resolver_serviceINS0_2ip3tcpEE7resolveERSt10shared_ptrIvERKNS3_20basic_resolver_queryIS4_EERNS_6system10error_codeE[_ZN5boost4asio6detail16resolver_serviceINS0_2ip3tcpEE7resolveERSt10shared_ptrIvERKNS3_20basic_resolver_queryIS4_EERNS_6system10error_codeE]+0xb1): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/usr/bin/ld: /usr/lib/gcc/x86_64-redhat-linux/6.2.1/libstdc++.a(eh_globals.o): undefined reference to symbol '__tls_get_addr@@GLIBC_2.3'
/usr/lib64/ld-linux-x86-64.so.2: error adding symbols: DSO missing from command line
```

### CODE REVIEW

**Comment by S74nk0** [comment]
Hi @kost. Thank you for your pull request. We will be pushing our Windows working branch and a **work in progress** Linux branch soon

**Comment by Rudd-O** [comment]
#NOOOOOOOOOOOOOOOOOOO!

I am not kost and I explicitly said not to merge this!!!!

READ THE COMMENT!!!!!!!!!!

**Comment by S74nk0** [comment]
@Rudd-O well write as @kost if you are @kost :)... no worries master is at Windows branch it works good. Linux is work in progress.

**Comment by kost** [comment]
Hello guys!

static compilation will always fail with new glibc (Debian/Ubuntu/Fedora/etc come with glibc by default). If you plan to statically compile, you need to use musl/uclibc based distro like Alpine. Take a look at my kost branch with instructions on how to do it under Alpine. Hope it helps!

**Comment by Rudd-O** [comment]
On 10/31/2016 02:38 AM, kost wrote:
>
> Hello guys!
>
> static compilation will always fail with new glibc
> (Debian/Ubuntu/Fedora/etc come with glibc by default). If you plan to
> statically compile, you need to use musl/uclibc based distro like
> Alpine. Take a look at my kost branch with instructions on how to do
> it under Alpine. Hope it helps!
>

That's false — statically compiled programs are totally possible in
Debian, Ubuntu and Fedora, all one needs to do is install the
corresponding -static package and that's it.

Pliease fix the bug I reported above.

-- 
    Rudd-O
    http://rudd-o.com/

**Pull request merged**
